# Generated by Django 3.1.3 on 2023-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('iconid', models.IntegerField()),
                ('revision_date', models.BigIntegerField()),
                ('puuid', models.CharField(max_length=78)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
