# Generated by Django 4.1.2 on 2023-02-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('updating', models.BooleanField()),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Puuid', models.CharField(max_length=78)),
                ('Level', models.IntegerField()),
                ('profile_img', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Tier', models.CharField(default='', max_length=20)),
                ('LP', models.IntegerField(default=0)),
                ('Win', models.IntegerField(default=0)),
                ('Top2', models.IntegerField(default=0)),
                ('sum_of_rank', models.IntegerField(default=0)),
                ('Total_game', models.IntegerField(default=0)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matchid', models.CharField(max_length=30)),
                ('Rank', models.IntegerField()),
                ('PetID', models.JSONField(max_length=40)),
                ('Pet_Img', models.CharField(max_length=50)),
                ('Game_level', models.IntegerField()),
                ('Traits', models.JSONField()),
                ('Augments', models.JSONField()),
                ('Units', models.JSONField()),
                ('Participant', models.JSONField()),
                ('Name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
