# Generated by Django 4.1.6 on 2023-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Participant',
            field=models.JSONField(),
        ),
    ]
