# Generated by Django 3.1.3 on 2023-01-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
                ('petID', models.CharField(max_length=40)),
                ('game_level', models.IntegerField()),
                ('traits', models.JSONField()),
                ('augments', models.JSONField()),
                ('units', models.JSONField()),
                ('participant1', models.CharField(max_length=20)),
                ('participant2', models.CharField(max_length=20)),
                ('participant3', models.CharField(max_length=20)),
                ('participant4', models.CharField(max_length=20)),
                ('participant5', models.CharField(max_length=20)),
                ('participant6', models.CharField(max_length=20)),
                ('participant7', models.CharField(max_length=20)),
                ('participant8', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
