# Generated by Django 3.1.3 on 2023-01-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='revision_date',
        ),
    ]
