# Generated by Django 4.1.2 on 2023-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='last_time',
            field=models.DateTimeField(),
        ),
    ]
