# Generated by Django 3.1.3 on 2023-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Participant1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant4',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant5',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant6',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant7',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='Participant8',
            field=models.CharField(max_length=25),
        ),
    ]
