# Generated by Django 4.1.6 on 2023-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_state_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
