# Generated by Django 3.1.3 on 2023-01-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='petID',
            field=models.JSONField(max_length=40),
        ),
    ]
