# Generated by Django 3.1.3 on 2023-01-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summoner_id',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=15)),
                ('LP', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('summoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
