# Generated by Django 3.1.3 on 2023-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230113_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summoner_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
