# Generated by Django 3.1.3 on 2023-01-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230113_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=30)),
                ('match', models.JSONField(null=True)),
            ],
        ),
    ]
