# Generated by Django 3.1.3 on 2023-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(max_length=15)),
                ('match_info', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_match',
        ),
    ]
