# Generated by Django 3.1.3 on 2023-01-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230118_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
                ('companion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='partner_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_placement', models.FloatField()),
                ('first_place', models.IntegerField()),
                ('duo_number', models.IntegerField()),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_match')),
            ],
        ),
    ]
