# Generated by Django 3.1.3 on 2023-01-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_partner_static_user_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_info',
            old_name='match_info',
            new_name='info',
        ),
    ]
